version: '3'
services:
  mysql:
    build:
      ./db/
    ports:
      - "3310:3306"
    environment:
      MYSQL_ROOT_PASSWORD: jgramajo202000895
      MYSQL_DATABASE: node_app_db
  frontend:
    build:
      ./docker
    ports:
      - "5000:8080"
